# Generated by Django 3.1.7 on 2021-03-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ti',
            field=models.CharField(default='ti', max_length=200),
        ),
    ]
