# Generated by Django 3.1.7 on 2021-03-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_ti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='ti',
        ),
    ]
