# Generated by Django 3.1.7 on 2021-03-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_principle'),
    ]

    operations = [
        migrations.AddField(
            model_name='principle',
            name='image',
            field=models.ImageField(default='C:/Users/wg/Documents/django_schoolapp_2.0/django_schoolapp2_pro/django_schoolapp2_pro/static/nobody.jpg', upload_to=''),
        ),
    ]
