# Generated by Django 3.1.7 on 2021-03-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20210305_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='image',
            field=models.ImageField(default='nobody.jpg', upload_to=''),
        ),
    ]
