# Generated by Django 3.1.7 on 2021-03-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_remove_principle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='principle',
            name='image',
            field=models.ImageField(default='nobody.jpg', upload_to=''),
        ),
    ]
