# Generated by Django 3.1.7 on 2021-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20210326_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='principle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
