# Generated by Django 3.1.7 on 2021-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_principle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
