# Generated by Django 3.1.7 on 2021-03-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_auto_20210326_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='image',
            field=models.ImageField(default='C:/Users/17085/OneDrive/Documents/django_school_pro2/schoolapp2/django_schoolapp2_pro/static/nobody.jpg', upload_to=''),
        ),
    ]
