# Generated by Django 3.1.7 on 2021-03-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_school_principle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='principle',
        ),
    ]
