# Generated by Django 3.1.7 on 2021-03-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_school_principle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='principle',
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(default='nobody.jpg', upload_to=''),
        ),
    ]
